gsap.set(".effect", { autoAlpha: 1 })
let tl = gsap.timeline()
  .from("h1", { scale: 0.01, duration: 4, ease: "power4.inOut" })
  .to(".blendImage, .bg", { scale: 0.6, duration: 3.5 }, 0)
  .to(".dark", { opacity: 0, duration: 2 }, ">-=100%")